name: contentblocks/plugin-detail
typeName: contentblocks_plugin_detail
prefixFields: true
prefixType: vendor
vendorPrefix: contentblocks
group: plugins
basics:
  - TYPO3/Appearance
  - TYPO3/Links
fields:
  -
    identifier: TYPO3/Header
    type: Basic
  -
    identifier: page_select
    type: Relation
    allowed: 'pages'
    relationship: manyToOne
