name: contentblocks/cta
table: tx_contentblocks_cta
title: Einzelner Link
prefixFields: true
prefixType: full
group: ContentBlocksHelper
security:
  ignorePageTypeRestriction: true
fields:
  - identifier: cta
    label: Linktext
    type: Text
    placeholder: Call to Action Text
  - identifier: url
    label: Linkziel
    type: Link
    autocomplete: true
    allowedTypes:
      - page
      - url
      - file
  - identifier: linklabel
    label: Nur Linklabel verlinken
    type: Checkbox
    renderType: checkboxLabeledToggle
    items:
      - label: 'Ausw√§hlen'
        labelChecked: 'Label ist verlinkt'
        labelUnchecked: 'Ganzer Teaser ist verlinkt'
        invertStateDisplay: false