name: hov/record2
table: tx_contentblocks_record1
prefixFields: false
typeName: record2
priority: 30
fields:
  - identifier: title
    type: Text
  - identifier: text
    type: Textarea
  - identifier: text3
    type: Textarea
